/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebacomponentesimple;

/**
 *
 * @author aleja
 */
public class Ciudades extends javax.swing.JDialog {

    /**
     * Creates new form Ciudades
     */
    public Ciudades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroup1.add(v1);
        buttonGroup1.add(v2);
        congratulations.setVisible(false);
        cancelar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        origenDestino1 = new componentecompuesto.OrigenDestino();
        jLabel1 = new javax.swing.JLabel();
        personas = new componentecompuesto.ComponenteCompuesto2();
        v1 = new javax.swing.JRadioButton();
        v2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        costo = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        congratulations = new javax.swing.JLabel();
        totalP = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        origenDestino1.setCiudades(new String[] {"Aguascalientes", "Sonora", "Veracruz", "Oaxaca", "CDMX"});
        origenDestino1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        origenDestino1.setTituloD("Ciudad Destino");
        origenDestino1.setTituloO("Ciudad Origen");

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setText("*Viajes - Venta de Boletos*");

        personas.setFEntero(true);
        personas.setFFlotante(false);
        personas.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        personas.setLongitud(4);
        personas.setTit1(true);
        personas.setTitulo("Cantidad de Personas");

        v1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        v1.setText("Viaje Redondo");
        v1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                v1ItemStateChanged(evt);
            }
        });
        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });

        v2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        v2.setText("Viaje Sencillo");
        v2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                v2ItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de Viaje:");

        calcular.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        costo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        costo.setText("Costo de un viaje: ");

        total.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        total.setText("Total:");

        congratulations.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        congratulations.setText("Recibes 10% de descuento");

        totalP.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        totalP.setText("Total a pagar: ");

        cancelar.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(origenDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(v1)
                                        .addGap(36, 36, 36)
                                        .addComponent(v2))
                                    .addComponent(costo)
                                    .addComponent(total)
                                    .addComponent(totalP)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calcular)
                                .addGap(18, 18, 18)
                                .addComponent(congratulations, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(origenDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(v1)
                    .addComponent(v2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(congratulations)
                    .addComponent(cancelar))
                .addGap(18, 18, 18)
                .addComponent(costo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalP)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public double dsto(double c ){
        double a = 0.1;
        return c-(c*a);
    }
    
    public void calcularTotal(double c1){
        int a = Integer.parseInt((String)personas.getDato(  ));
        double b = a*c1;
        if (v1.isSelected()){
            total.setText("Total:              " + (b*2));
            totalP.setText("Total a pagar:      "+dsto(b*2));
        }else {
            total.setText("Total:              " + (b));
            totalP.setText("Total a pagar:      "+(b));
        }
    }
    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        String origen = origenDestino1.getOrigen();
        String destino = origenDestino1.getDestino();
        if (origen.equalsIgnoreCase("AGUASCALIENTES") && destino.equalsIgnoreCase("Sonora") || 
                origen.equalsIgnoreCase("SONORA") && destino.equalsIgnoreCase("AGUASCALIENTES") ){
            double c1 = 750;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1);
        }
        if (origen.equalsIgnoreCase("AGUASCALIENTES") && destino.equalsIgnoreCase("VERACRUZ") || 
                origen.equalsIgnoreCase("VERACRUZ") && destino.equalsIgnoreCase("AGUASCALIENTES") ){
            double c1 = 550;
            costo.setText("Costo de un boleto:  " +c1);
        }
        if (origen.equalsIgnoreCase("AGUASCALIENTES") && destino.equalsIgnoreCase("OAXACA") || 
                origen.equalsIgnoreCase("OAXACA") && destino.equalsIgnoreCase("AGUASCALIENTES") ){
            double c1 = 850;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1);
        }
        if (origen.equalsIgnoreCase("AGUASCALIENTES") && destino.equalsIgnoreCase("CDMX") || 
                origen.equalsIgnoreCase("CDMX") && destino.equalsIgnoreCase("AGUASCALIENTES") ){
            double c1 = 355;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1);
        }
        if (origen.equalsIgnoreCase("AGUASCALIENTES") && destino.equalsIgnoreCase("CDMX") || 
                origen.equalsIgnoreCase("CDMX") && destino.equalsIgnoreCase("AGUASCALIENTES") ){
            double c1 = 355;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1);
        }
        if (origen.equalsIgnoreCase("SONORA") && destino.equalsIgnoreCase("VERACRUZ") || 
                origen.equalsIgnoreCase("VERACRUZ") && destino.equalsIgnoreCase("SONORA") ){
            double c1 = 1050;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1);
        }
        if (origen.equalsIgnoreCase("SONORA") && destino.equalsIgnoreCase("OAXACA") || 
                origen.equalsIgnoreCase("OAXACA") && destino.equalsIgnoreCase("SONORA") ){
            double c1 = 2781;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1);
        }
        if (origen.equalsIgnoreCase("SONORA") && destino.equalsIgnoreCase("CDMX") || 
                origen.equalsIgnoreCase("CDMX") && destino.equalsIgnoreCase("SONORA") ){
            double c1 = 897;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1);
        }
        if (origen.equalsIgnoreCase("VERACRUZ") && destino.equalsIgnoreCase("OAXACA") || 
                origen.equalsIgnoreCase("OAXACA") && destino.equalsIgnoreCase("VERACRUZ") ){
            double c1 = 342;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1);
        }
        if (origen.equalsIgnoreCase("VERACRUZ") && destino.equalsIgnoreCase("CDMX") || 
                origen.equalsIgnoreCase("CDMX") && destino.equalsIgnoreCase("VERACRUZ") ){
            double c1 = 561;
            costo.setText("Costo de un boleto:  " +c1);
            calcularTotal(c1); 
        }
        if (origen.equalsIgnoreCase("OAXACA") && destino.equalsIgnoreCase("CDMX") || 
                origen.equalsIgnoreCase("CDMX") && destino.equalsIgnoreCase("OAXACA") ){
            double c1 = 761;
            costo.setText("Costo de un boleto:  " +c1);calcularTotal(c1);
        }
        calcular.setVisible(false);
        origenDestino1.setActive(false);
        personas.setActive(false);
        v1.setEnabled(false);
        v2.setEnabled(false);
        cancelar.setVisible(true);
    }//GEN-LAST:event_calcularActionPerformed

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v1ActionPerformed

    private void v1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_v1ItemStateChanged
        if (v1.isSelected()){
            congratulations.setVisible(true);
        }
    }//GEN-LAST:event_v1ItemStateChanged

    private void v2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_v2ItemStateChanged
         if (v2.isSelected()){
            congratulations.setVisible(false);
        }
    }//GEN-LAST:event_v2ItemStateChanged

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        cancelar.setVisible(false);
        origenDestino1.setActive(true);
        personas.setActive(true);
        v1.setEnabled(true);
        v2.setEnabled(true);
        calcular.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ciudades dialog = new Ciudades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcular;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel congratulations;
    private javax.swing.JLabel costo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private componentecompuesto.OrigenDestino origenDestino1;
    private componentecompuesto.ComponenteCompuesto2 personas;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalP;
    private javax.swing.JRadioButton v1;
    private javax.swing.JRadioButton v2;
    // End of variables declaration//GEN-END:variables
}
